### ISSUE TITLE
rejected blocks when "rewardRecipients" are enabled and setup

### ISSUE THREAD

**Issue by 49handyman** [webworker01/node-stratum-pool#7]
I'm revisiting this since I tried to set up new ```rewardRecipients``` this week to separate taddresses. I first tried 3 recipients and about 58% of blocks found were REJECTED. 

```
[11/4/2021, 8:49:58 PM] [ESC[32minfoESC[39m] [pirate-chain] [Pool [:1]] : Stratum Pool Server Started for pirate-chain [ARRR] 
                                                Network Connected:      Mainnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   1636648
                                                Current Block Diff:     5853202.373335338
                                                Current Connect Peers:  20
                                                Network Difficulty:     2783667236.217002
                                                Network Hash Rate:      594.66 MH
                                                Stratum Port(s):        3347, 3348
                                                Pool Fee Percent:       15%

```

```
"rewardRecipients": {
 "RLdddne52NzYbbXBKC9uDFtQwGg1SPetxV": .05,
 "RCcewCoWpUPq9XzpMBgHsvPV1q4Utbn1on": .05,
 "RGFdfU7BTtDLSmZHkQq66bKgVQDAQNNFJZ": .05
}, 
```

I can run months without a rejected block normally with no rewardRecipients set (see attached logs).

I tested 3 pool servers with different configurations (1 and 3 rewardRecipients), each had rejected blocks (within 2 hours) once they were restarted with the new pirate config. Once I removed the rewardRecipients and restarted the pool server I have not had a rejected block since. Actually you rarely see REJECTED blocks. In the last 5 months, I have 9 total on one server, and 11 (10 were REJECTED while testing)  total on another server and most were last week while I was running with rewardRecipients enabled. Not all blocks are rejected and that's what's got me so confused. but you can review the logs for yourself. 

42% of the blocks were accepted fine. you can see about 18 good block with rewardRecipients enabled, which matches my logs  here:

[http://pool.entrustus.org:7782/address/RLdddne52NzYbbXBKC9uDFtQwGg1SPetxV](http://pool.entrustus.org:7782/address/RLdddne52NzYbbXBKC9uDFtQwGg1SPetxV)

If that server isn't public just copy the transaction in the URL to your Pirate's  explorer. I just counted 18 successful blocks.

I did some debugging in the past for you when I brought it up about 5 months ago. The problem was the coinbase was off by the amount of the rewardRecipients, so the block was rejected. I think...

If you let me know how to re-enable the debugging, while  rewardRecipients  is enabled, I can get you a fresh information on the REJECTED transaction/coinbase data submitted. I have plenty of time to work on this.  it shouldn't take more the 2-5 hours for a rejected block to be logged.

I have reviewed most of the JS code involved in creating the coinbase transaction and rewardRecipients in the node-stratum code. However, I'm not a good experienced JS developer. Just a hack!

When 3 - 5% rewardRecipients  (.05) are enabled, pool server starts properly and show a total of 15% being taken as fees.

I know the logs attached don't tell you why, but i wanted you to see that REJECTED blocks rarely happen with no "rewardRecipients" setup. I tried to only include pertinent logs also.

[rejected_blocks_pm2_logs.txt](https://github.com/webworker01/node-stratum-pool/files/7565965/rejected_blocks_pm2_logs.txt)

**Comment by webworker01** [comment]
![image](https://user-images.githubusercontent.com/3256000/142506702-67f0ec8e-de8d-4426-96f7-08330e5301d2.png)
